Repository here-y-seo/Team6, pull requests merged in 2022-08, with the labels that each got.

#3 [Chore] #2 - 앱 아이콘 변경
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: ☁️YunDol☁️, Chore

#17 [Design] #4 - Splash 뷰 UI 구현
  SMSH-Summer/SMSH-Summer.xcodeproj/project.pbxproj
  SMSH-Summer/SMSH-Summer/Application/ModuleFactory/Factory/ModuleFactory.swift
  SMSH-Summer/SMSH-Summer/Application/SceneDelegate.swift
  SMSH-Summer/SMSH-Summer/Global/Literals/StoryboardLiterals.swift
  SMSH-Summer/SMSH-Summer/Presentation/Main/VC/Base.lproj/Main.storyboard
  SMSH-Summer/SMSH-Summer/Presentation/Splash/VC/Splash.storyboard
  SMSH-Summer/SMSH-Summer/Presentation/Splash/VC/SplashVC.swift
Labels: ☁️YunDol☁️, Design

#19 [Design] #9 - 목록보기 뷰 UI 구현
  SMSH-Summer/SMSH-Summer.xcodeproj/project.pbxproj
  SMSH-Summer/SMSH-Summer/Application/ModuleFactory/Factory/ModuleFactory.swift
  SMSH-Summer/SMSH-Summer/Application/SceneDelegate.swift
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/icon-filter.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/icon-filter.imageset/icon-filter@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/icon-filter.imageset/icon-filter@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/icon-filter.imageset/icon-filter@3x.png
  SMSH-Summer/SMSH-Summer/Presentation/List/VC/ListCollectionViewCell.swift
  SMSH-Summer/SMSH-Summer/Presentation/List/VC/ListViewController.swift
Labels: Design, 🫧Doy🫧

#22 #20 - [Design] 권한설정 뷰 UI
  SMSH-Summer/SMSH-Summer.xcodeproj/project.pbxproj
  SMSH-Summer/SMSH-Summer/Application/ModuleFactory/Factory/ModuleFactory.swift
  SMSH-Summer/SMSH-Summer/Application/SceneDelegate.swift
  SMSH-Summer/SMSH-Summer/Presentation/Authorization/VC/AuthorizationViewController.swift
Labels: Design, 🫧Doy🫧

#24 #21 - [Feat] 권한설정 기능 구현
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-animal-mini-marker.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-animal-mini-marker.imageset/icon-animal-mini-marker@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-animal-mini-marker.imageset/icon-animal-mini-marker@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-animal-mini-marker.imageset/icon-animal-mini-marker@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-animal-mini.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-animal-mini.imageset/icon-animal-mini@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-animal-mini.imageset/icon-animal-mini@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-animal-mini.imageset/icon-animal-mini@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-donation-mini-marker.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-donation-mini-marker.imageset/icon-donation-mini-marker@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-donation-mini-marker.imageset/icon-donation-mini-marker@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-donation-mini-marker.imageset/icon-donation-mini-marker@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-donation-mini.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-donation-mini.imageset/icon-donation-mini@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-donation-mini.imageset/icon-donation-mini@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-donation-mini.imageset/icon-donation-mini@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-etc-mini-marker.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-etc-mini-marker.imageset/icon-etc-mini-marker@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-etc-mini-marker.imageset/icon-etc-mini-marker@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-etc-mini-marker.imageset/icon-etc-mini-marker@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-etc-mini.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-etc-mini.imageset/icon-etc-mini@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-etc-mini.imageset/icon-etc-mini@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-etc-mini.imageset/icon-etc-mini@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-location-overlay.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-location-overlay.imageset/icon-location-overlay@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-location-overlay.imageset/icon-location-overlay@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-location-overlay.imageset/icon-location-overlay@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-plogging-mini-marker.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-plogging-mini-marker.imageset/icon-plogging-mini-marker@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-plogging-mini-marker.imageset/icon-plogging-mini-marker@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-plogging-mini-marker.imageset/icon-plogging-mini-marker@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-plogging-mini.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-plogging-mini.imageset/icon-plogging-mini@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-plogging-mini.imageset/icon-plogging-mini@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-plogging-mini.imageset/icon-plogging-mini@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-volunteer-mini-marker.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-volunteer-mini-marker.imageset/icon-volunteer-mini-marker@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-volunteer-mini-marker.imageset/icon-volunteer-mini-marker@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-volunteer-mini-marker.imageset/icon-volunteer-mini-marker@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-volunteer-mini.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-volunteer-mini.imageset/icon-volunteer-mini@1x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-volunteer-mini.imageset/icon-volunteer-mini@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/icon-volunteer-mini.imageset/icon-volunteer-mini@3x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/isActivated=False, Kind=04.imageset/isActivated=False, Kind=04.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/isActivated=False, Kind=04.imageset/isActivated=False, Kind=04@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Map/isActivated=False, Kind=04.imageset/isActivated=False, Kind=04@3x.png
  SMSH-Summer/SMSH-Summer/Info.plist
  SMSH-Summer/SMSH-Summer/Presentation/Authorization/VC/AuthorizationViewController.swift
  SMSH-Summer/SMSH-Summer/Presentation/Home/VC/HomeViewController.swift
Labels: Feat, 🫧Doy🫧

#27 [Feat] #5 - 탭 바 구현
  SMSH-Summer/SMSH-Summer.xcodeproj/project.pbxproj
  SMSH-Summer/SMSH-Summer/Application/ModuleFactory/Factory/ModuleFactory.swift
  SMSH-Summer/SMSH-Summer/Application/SceneDelegate.swift
  SMSH-Summer/SMSH-Summer/Global/Extention/Design/UIColor+.swift
  SMSH-Summer/SMSH-Summer/Global/Literals/StoryboardLiterals.swift
  SMSH-Summer/SMSH-Summer/Global/Resources/Colors.xcassets/tabBarUnSelected.colorset/Contents.json
  SMSH-Summer/SMSH-Summer/Presentation/Home/VC/Home.storyboard
  SMSH-Summer/SMSH-Summer/Presentation/List/VC/List.storyboard
  SMSH-Summer/SMSH-Summer/Presentation/TabBar/customTabBar.swift
  SMSH-Summer/SMSH-Summer/Presentation/TabBar/tabBar.storyboard
Labels: ☁️YunDol☁️, Feat

#32 [Design #31 - 종류 선택 창 만들기
  SMSH-Summer/SMSH-Summer.xcodeproj/project.pbxproj
  SMSH-Summer/SMSH-Summer/Application/ModuleFactory/Factory/ModuleFactory.swift
  SMSH-Summer/SMSH-Summer/Application/SceneDelegate.swift
  SMSH-Summer/SMSH-Summer/Global/Literals/StoryboardLiterals.swift
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Write/etcDisableBtn.imageset/Contents.json
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Write/etcDisableBtn.imageset/isActivated=False, Kind=05.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Write/etcDisableBtn.imageset/isActivated=False, Kind=05@2x.png
  SMSH-Summer/SMSH-Summer/Global/Resources/Assets.xcassets/Write/etcDisableBtn.imageset/isActivated=False, Kind=05@3x.png
  SMSH-Summer/SMSH-Summer/Presentation/TabBar/customTabBar.swift
  SMSH-Summer/SMSH-Summer/Presentation/typeSelect/typeSelect.storyboard
  SMSH-Summer/SMSH-Summer/Presentation/typeSelect/typeSelectVC.swift
Labels: ☁️YunDol☁️, Design
